### ISSUE TITLE
Placeholder char is added to value

### ISSUE THREAD

**Issue by pduersteler** [angular-ui/ui-mask#102]
If I set `_` as a placeholder value and define a mask for accepting e.g. phone numbers from various countries (which have different lenghts) by setting a mask like `+99 99999999?9?9?` and the entered value is not as long as it could be, the placeholder chars are also submitted.

So, for entering e.g. `+41 1111111`, I actually get `+41 1111111__` as value in the model and in the form submitted therefore, which, at least for me, seems quite wrong. IMHO I should get what I entered, without the optional placeholder chars appended.

**Comment by lukepfeiffer10** [comment]
A sample plunkr would be helpful to clarify exactly how you are using the directive.

**Comment by lukepfeiffer10** [comment]
@pduersteler Are you setting `modelViewValue="true"` on your input? This sets the model value to be the same as the view value which explains the placeholder characters in the model because the view value contains those placeholders. Otherwise, (`modelViewValue="false"`) the model value does not contain any of the placeholder characters even though the view value does.

**Comment by bsssshhhhhhh** [comment]
I've noticed this issue as well - it would be nice for ui-mask to have the option of automatically removing optional placeholder characters from the model if they aren't used, while still keeping the non-optional ones that are used.

With a mask of `(999) 999-9999 ?x?9?9?9?9?9` and an input of `1234567890`, I want the model to be set to `(123) 456-7890`, but instead it is set to `(123) 456-7890 x_____`. With the same mask and an input of `1234567890123`, I want the model set to `(123) 456-7890 x123`, but it is set to `(123) 456-7890 x123__`. Having the placeholder characters (`_`) is nice, but only on the input side, as it is only useful to the user. Setting `modelViewValue` to false sets the model `1234567890`, which requires me to format it myself in order to get the output I want -- extra complexity.

Hope I explained what I'm trying to accomplish, let me know if I can help clarify or resolve this. Thanks

**Comment by lukepfeiffer10** [comment]
@bsssshhhhhhh I'm hesitant to make this change as it makes the `modelViewValue` attribute's functionality a little ambiguous.

I think it's possible to do this but I don't know if it should be done.

**Comment by bsssshhhhhhh** [comment]
Maybe add an extra option for it, defaulting to its current behavior? If it can be done and there's a desire for it, then why not?

**Comment by lukepfeiffer10** [comment]
Code complexity and ease of use come to mind as why not to add another one off option.

**Comment by bsssshhhhhhh** [comment]
Ok no problem, I just added a simple parser that takes care of it for this case. For other input masks you'll need to change the regex around to fit your needs:

```
directive('phoneMask', function ($compile) {
	return {
		restrict: 'A',
		require: 'ngModel',
		replace: false,
		priority: 1000,

		link: function(scope, element, attrs, ngModel) {
			ngModel.$parsers.push(function(value) {
				if (ngModel.$modelValue && ngModel.$modelValue !== '') {
					value = value.replace(/([\s]x[_]+|[_]+$)/, '');
				}
				return value;
			});

			element.attr('ui-mask', '(999) 999-9999 ?x?9?9?9?9?9');
			element.attr('model-view-value', 'true');
			element.attr('ui-mask-placeholder', ' ');
			element.attr('allow-invalid-value', 'true');

			element.removeAttr('phone-mask');
			$compile(element)(scope);
		}
	};
});
```
