### ISSUE TITLE
Conditional mask applied on key event

### ISSUE THREAD

**Issue by erinzobitz** [angular-ui/ui-mask#148]
I want to support both standard CC formats (9999 9999 9999 9999) and Amex (9999 999999 99999). I'm using the first character entered to set a `creditCardProvider` scope variable to determine the mask, i.e. 3 for Amex mask. However, when it conditionally applies the mask to support Amex it clears the input field or the new mask overrides. Any thoughts on how to tackle? I would imagine someone has had to handle a similar issue before. 

```
<input
    type="tel"
    name="creditCard"
    pattern="\d*"
    ng-model="model.billing_info.number"
    ng-keyup="setCreditCardProvider($event)"
    ng-pattern="/1|(^3[47])|(^(36|38|30[0-5]))|(^(6011|65|64[4-9]|622))|(^5[1-5])|(^4)/"
    ui-options="{clearOnBlur: false}"
    ui-mask="{{view.creditCardProvider === 'Amex' ? '9999 999999 99999' : '9999 9999 9999 9999'}}"
    ui-mask-placeholder
    format-credit-card
    required>
```

**Comment by lukepfeiffer10** [comment]
Unfortunately the only think I can think of that will work with how the library currently functions is a bit hacky.

1. Set up the `ui-mask` to be bound to a variable instead of the expression like you have.
2. Create a watch on that variable.
3. In `setCreditCardProvider` have it also set a variable that is the current view value.
4. When the `ui-mask` variable watch executes set the model value `model.billing_info.number` to the variable that you set in `setCreditCardProvider`.

I think this will work. Haven't tested it yet but it's the only thing I can think of that will potentially work for this scenario.

**Comment by erinzobitz** [comment]
Thanks @lukepfeiffer10!

**Comment by lukepfeiffer10** [comment]
@erinzobitz Sorry this took so long but try out the new `allowInvalidValue` in the latest 1.8.4 tag and see if that fixes your issue.
