### ISSUE TITLE
When initializing the mask it is set to dirty

### ISSUE THREAD

**Issue by marbletravis** [angular-ui/ui-mask#29]
When initializing the mask it is set to dirty even though technically the data hasn't changed.

In initPlaceHolder function eventHandler is called which ends up setting the field as dirty. It appears in other initialization sequences that we don't want it set to dirty.

Bug?

**Comment by meyerds** [comment]
I'm also seeing this issue. It seems to happen in IE11 only. Chrome 44 and Firefox 29 do not set the $dirty flag.

The offending line of code is "controller.$setViewValue(valUnmasked)"

**Comment by marbletravis** [comment]
@meyerds I am not seeing the issue with v1.4.2 in IE 11 specifically version below.
![image](https://cloud.githubusercontent.com/assets/8137075/9361405/89064cbc-4658-11e5-9d57-0da7909fcb8b.png)

I wouldn't mind helping you figure this out. Can you provide more information, Just to clarify $dirty should be set when a user edits the field, but not when the field is being initialized.

**Comment by fabioginzel** [comment]
+1

**Comment by fallXone** [comment]
There was an issue in IE where a placeholder input would fire the 'input' event initially, dirtying the form. It makes UI-mask look like the culprit, but I believe IE is to blame. The angular team fixed this in angular 1.3.6.

**Comment by MikeMatusz** [comment]
Using ui.mask 1.6.7 and Angular 1.4.4 I'm still seeing this issue in IE11 on an input with a phone number mask.  The input event is still firing with the oldValue as '(___)___-____', it enters the "User attempted to delete but raw value was unaffected" block and sets valAltered = true.  I think this could be handled easily just by checking if the new valUnmasked is any different from valUnmaskedOld and not setting valAltered if they are still the same, since the value has not, in fact, been altered.

I don't think the angular fix handles all scenarios, as they still have an open item: https://github.com/angular/angular.js/issues/7726, which links to a Microsoft bug that is marked fixed in Edge (but not IE10,11,etc.).

Will you consider reopening this issue? I'd be happy to submit a pull request with the fix.

**Comment by Vaaceph** [comment]
Hi, I am getting same Issue with Angular2/4, can anyone help me with it?
