### ISSUE TITLE
ui-mask-placeholder (or regular placeholder) attributes get confused when typing a character in the placeholder

### ISSUE THREAD

**Issue by wiltzius** [angular-ui/ui-mask#32]
Splitting from issue #25 

Modified plunkr example demonstrating the remaining bug:

http://plnkr.co/edit/CDG941601WdHPMEdlEdG?p=preview

Example invocation:

`<input ui-mask="(999) 999-9999" ng-model="c" placeholder="Phone number" ui-mask-placeholder="(555) 555-5555"/>`

Try typing in the box starting with "650" and you'll see the error -- it gets messed up if you type a key that's in the placeholder. If you enter "678987" etc it works fine.

**Comment by cleever** [comment]
+1

**Comment by gustavolira** [comment]
+1

**Comment by glebmachine** [comment]
+1

**Comment by nikoloza** [comment]
+1

**Comment by kdorion** [comment]
+1

**Comment by alexw23** [comment]
+1

**Comment by Eversilence** [comment]
+1

**Comment by adairborba** [comment]
+1

**Comment by JohnyNogueira** [comment]
+1

**Comment by lukepfeiffer10** [comment]
This is what I've found so far. 

I'll be using the placeholder `(555) 555-5555` for this below discussion and the value I'll be trying to input is `650`.

When the value is being unmasked in the `unmaskValue` function, there is a `replace` call on the current string value. This is because when you originally input a value it is simply added to the string meaning a placeholder of `(555) 555-5555` turns into `(6555) 555-5555` when entering the number 6. The call to `replace` removes the **first** extraneous 5 resulting in `(655) 555-5555.

Now, if you want to add a 5 to the string it appears to function correctly (in reality the 5 that was entered was actually replaced but since it matches the placeholder it is unnoticeable). The problem arises when you need to add another character after that added 5. Upon entering the next character, a 0 in this case, the new value is not what would be expected. Instead of the value changing from `(655) 555-5555` to `(650) 555-5555`, the value actually turns out to be `(605) 555-5555`.

The cause behind this is that pesky `replace` function in `unmaskValue` (I use pesky here loosely as it is rather vital in the normal operation of the library). Now, stepping through the `unmaskValue` function the value string supplied as the argument is `(6505) 555-5555` which is as expected. However, when calling `replace` it replaces the **first** matched occurrence of the placeholder character, 5, resulting in the unintended string of `(605) 555-5555`.

**Possible solutions:**

Make the replace call starts at the current caret position. Potential issues with this come from if the user is not actually adding characters but only moving the caret which could cause problems and bad values. Could check to see if there was an addition before calling `unmaskValue` in the `eventHandler` but I can't be sure of the repercussions of doing that. In that case what do you set as the unmasked value? Should most of the normal processing be skipped and just the caret re-position code be run?

I would love to get some feedback on this if the maintainers have some time to look it over. If they like my idea I will go ahead and give it a shot to see if this issue can be fixed.
